services:
  - type: web
    name: telegram-streamer-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install --default-timeout=100 -r requirements.txt"
    startCommand: "python3 -m kunal"
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: BIN_CHANNEL
        sync: false
      - key: NEW_USER_LOG
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: OWNER_ID
        sync: false
      - key: OWNER_USERNAME
        sync: false
      - key: UPDATES_CHANNEL
        value: "None"
      - key: ON_HEROKU
        value: "True"
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: URL
        sync: false
